/**
 * @jest-environment node
 *
 * .env.example と NEXT_PUBLIC_* 変数の整合性チェック。
 *
 * 【運用方針】
 * 本リポジトリでは、「iThiel Committee」および「C3」の実運用に必要な基本設定
 * （サイト情報、AI、音声、モデル等のコア設定）のみに `.env.example` を絞り込んでいます。
 *
 * AITuberKit由来のオプショナル機能・段階的整理対象機能（YouTube連携、ゲーム実況、
 * スライド、キオスク、Live2D/PNGTuber、人感検知、長期記憶等）に関する環境変数は
 * `EXCLUDED_FROM_ENV_EXAMPLE` として明示的に管理し、未管理の変数が勝手に追加されることを防ぎます。
 *
 * また、`.env.example` に宣言されている変数は、コードから実際に参照されている（staleではない）
 * ことを保証します。
 */
import fs from 'fs'
import path from 'path'

const ENV_EXAMPLE_PATH = path.join(process.cwd(), '.env.example')
const SRC_DIR = path.join(process.cwd(), 'src')

// .env.example にのみ存在してよい（コードから直接参照されない）変数。
// 追加する場合は理由をコメントで明記すること。
const ALLOWED_UNREFERENCED_IN_CODE: string[] = []

/**
 * .env.example から意図的に除外されているオプショナル・段階的整理対象の環境変数。
 * 機能削除やスリム化が進んだ際は、このリストからも削除すること。
 */
const EXCLUDED_FROM_ENV_EXAMPLE: string[] = [
  // --- AivisSpeech / Aivis Cloud ---
  'NEXT_PUBLIC_AIVIS_CLOUD_INTONATION_SCALE',
  'NEXT_PUBLIC_AIVIS_CLOUD_MODEL_UUID',
  'NEXT_PUBLIC_AIVIS_CLOUD_PITCH',
  'NEXT_PUBLIC_AIVIS_CLOUD_POST_PHONEME_LENGTH',
  'NEXT_PUBLIC_AIVIS_CLOUD_PRE_PHONEME_LENGTH',
  'NEXT_PUBLIC_AIVIS_CLOUD_SPEED',
  'NEXT_PUBLIC_AIVIS_CLOUD_STYLE_ID',
  'NEXT_PUBLIC_AIVIS_CLOUD_STYLE_NAME',
  'NEXT_PUBLIC_AIVIS_CLOUD_TEMPO_DYNAMICS',
  'NEXT_PUBLIC_AIVIS_CLOUD_USE_STYLE_NAME',
  'NEXT_PUBLIC_AIVIS_SPEECH_INTONATION_SCALE',
  'NEXT_PUBLIC_AIVIS_SPEECH_PITCH',
  'NEXT_PUBLIC_AIVIS_SPEECH_POST_PHONEME_LENGTH',
  'NEXT_PUBLIC_AIVIS_SPEECH_PRE_PHONEME_LENGTH',
  'NEXT_PUBLIC_AIVIS_SPEECH_SPEAKER',
  'NEXT_PUBLIC_AIVIS_SPEECH_SPEED',
  'NEXT_PUBLIC_AIVIS_SPEECH_TEMPO_DYNAMICS',

  // --- 音声・TTS（その他） ---
  'NEXT_PUBLIC_AUDIO_MODE',
  'NEXT_PUBLIC_AUDIO_MODE_INPUT_TYPE',
  'NEXT_PUBLIC_AUDIO_MODE_VOICE',
  'NEXT_PUBLIC_GOOGLE_TTS_TYPE',
  'NEXT_PUBLIC_KOEIROMAP_KEY',
  'NEXT_PUBLIC_OPENAI_TTS_MODEL',
  'NEXT_PUBLIC_OPENAI_TTS_SPEED',
  'NEXT_PUBLIC_OPENAI_TTS_VOICE',
  'NEXT_PUBLIC_STYLEBERTVITS2_LENGTH',
  'NEXT_PUBLIC_STYLEBERTVITS2_MODEL_ID',
  'NEXT_PUBLIC_STYLEBERTVITS2_SDP_RATIO',
  'NEXT_PUBLIC_STYLEBERTVITS2_STYLE',

  // --- Azure / 外部API ---
  'NEXT_PUBLIC_AZURE_API_KEY',
  'NEXT_PUBLIC_AZURE_ENDPOINT',
  'NEXT_PUBLIC_AZURE_KEY',
  'NEXT_PUBLIC_CUSTOM_API_BODY',
  'NEXT_PUBLIC_CUSTOM_API_HEADERS',
  'NEXT_PUBLIC_CUSTOM_API_INCLUDE_MIME_TYPE',
  'NEXT_PUBLIC_CUSTOM_API_URL',
  'NEXT_PUBLIC_CUSTOM_MODEL',

  // --- YouTube連携 ---
  'NEXT_PUBLIC_YOUTUBE_API_KEY',
  'NEXT_PUBLIC_YOUTUBE_COMMENT_INTERVAL',
  'NEXT_PUBLIC_YOUTUBE_COMMENT_SOURCE',
  'NEXT_PUBLIC_YOUTUBE_LIVE_ID',
  'NEXT_PUBLIC_YOUTUBE_MODE',
  'NEXT_PUBLIC_ONECOMME_PORT',

  // --- 会話継続ワークフロー ---
  'NEXT_PUBLIC_CONVERSATION_CONTINUITY_NEW_TOPIC_THRESHOLD',
  'NEXT_PUBLIC_CONVERSATION_CONTINUITY_PROMPT_CONTINUATION',
  'NEXT_PUBLIC_CONVERSATION_CONTINUITY_PROMPT_EVALUATE',
  'NEXT_PUBLIC_CONVERSATION_CONTINUITY_PROMPT_NEW_TOPIC',
  'NEXT_PUBLIC_CONVERSATION_CONTINUITY_PROMPT_SELECT_COMMENT',
  'NEXT_PUBLIC_CONVERSATION_CONTINUITY_PROMPT_SLEEP',
  'NEXT_PUBLIC_CONVERSATION_CONTINUITY_SLEEP_THRESHOLD',

  // --- ゲーム実況 ---
  'NEXT_PUBLIC_GAME_COMMENTARY_BACKGROUND_ANALYSIS_ENABLED',
  'NEXT_PUBLIC_GAME_COMMENTARY_BACKGROUND_ANALYSIS_INTERVAL',
  'NEXT_PUBLIC_GAME_COMMENTARY_BACKGROUND_ANALYSIS_PROMPT_TEMPLATE',
  'NEXT_PUBLIC_GAME_COMMENTARY_CAPTURE_INTERVAL',
  'NEXT_PUBLIC_GAME_COMMENTARY_CONTEXT_COUNT',
  'NEXT_PUBLIC_GAME_COMMENTARY_ENABLED',
  'NEXT_PUBLIC_GAME_COMMENTARY_IMAGE_QUALITY',
  'NEXT_PUBLIC_GAME_COMMENTARY_PROMPT_TEMPLATE',
  'NEXT_PUBLIC_GAME_COMMENTARY_RESIZE_WIDTH',
  'NEXT_PUBLIC_GAME_COMMENTARY_SAVE_TO_CHAT',

  // --- スライド機能 ---
  'NEXT_PUBLIC_SLIDE_MODE',

  // --- キオスクモード ---
  'NEXT_PUBLIC_KIOSK_GUIDANCE_MESSAGE',
  'NEXT_PUBLIC_KIOSK_GUIDANCE_TIMEOUT',
  'NEXT_PUBLIC_KIOSK_MAX_INPUT_LENGTH',
  'NEXT_PUBLIC_KIOSK_MODE_ENABLED',
  'NEXT_PUBLIC_KIOSK_NG_WORDS',
  'NEXT_PUBLIC_KIOSK_NG_WORD_ENABLED',
  'NEXT_PUBLIC_KIOSK_PASSCODE',

  // --- 人感検知（Presence Detection） ---
  'NEXT_PUBLIC_PRESENCE_CLEAR_CHAT_ON_DEPARTURE',
  'NEXT_PUBLIC_PRESENCE_COOLDOWN_TIME',
  'NEXT_PUBLIC_PRESENCE_DEBUG_MODE',
  'NEXT_PUBLIC_PRESENCE_DEPARTURE_MESSAGE',
  'NEXT_PUBLIC_PRESENCE_DEPARTURE_TIMEOUT',
  'NEXT_PUBLIC_PRESENCE_DETECTION_ENABLED',
  'NEXT_PUBLIC_PRESENCE_DETECTION_SENSITIVITY',
  'NEXT_PUBLIC_PRESENCE_DETECTION_THRESHOLD',
  'NEXT_PUBLIC_PRESENCE_GREETING_MESSAGE',
  'NEXT_PUBLIC_PRESENCE_SELECTED_CAMERA_ID',

  // --- アイドルモード ---
  'NEXT_PUBLIC_IDLE_AI_GENERATION_ENABLED',
  'NEXT_PUBLIC_IDLE_AI_PROMPT_TEMPLATE',
  'NEXT_PUBLIC_IDLE_DEFAULT_EMOTION',
  'NEXT_PUBLIC_IDLE_INTERVAL',
  'NEXT_PUBLIC_IDLE_MODE_ENABLED',
  'NEXT_PUBLIC_IDLE_MOTION_GROUP',
  'NEXT_PUBLIC_IDLE_PLAYBACK_MODE',
  'NEXT_PUBLIC_IDLE_TIME_PERIOD_AFTERNOON',
  'NEXT_PUBLIC_IDLE_TIME_PERIOD_ENABLED',
  'NEXT_PUBLIC_IDLE_TIME_PERIOD_EVENING',
  'NEXT_PUBLIC_IDLE_TIME_PERIOD_MORNING',

  // --- 長期記憶 / RAG ---
  'NEXT_PUBLIC_MEMORY_ENABLED',
  'NEXT_PUBLIC_MEMORY_MAX_CONTEXT_TOKENS',
  'NEXT_PUBLIC_MEMORY_SEARCH_LIMIT',
  'NEXT_PUBLIC_MEMORY_SIMILARITY_THRESHOLD',

  // --- Live2D & PNGTuber ---
  'NEXT_PUBLIC_LIVE2D_ENABLED',
  'NEXT_PUBLIC_SELECTED_LIVE2D_PATH',
  'NEXT_PUBLIC_PNGTUBER_CHROMA_KEY_COLOR',
  'NEXT_PUBLIC_PNGTUBER_CHROMA_KEY_ENABLED',
  'NEXT_PUBLIC_PNGTUBER_CHROMA_KEY_TOLERANCE',
  'NEXT_PUBLIC_PNGTUBER_OFFSET_X',
  'NEXT_PUBLIC_PNGTUBER_OFFSET_Y',
  'NEXT_PUBLIC_PNGTUBER_SCALE',
  'NEXT_PUBLIC_PNGTUBER_SENSITIVITY',
  'NEXT_PUBLIC_SELECTED_PNGTUBER_PATH',

  // --- 外部連携・埋め込み・公式サイト ---
  'NEXT_PUBLIC_AITUBERKIT_API_KEY',
  'NEXT_PUBLIC_AITUBERKIT_DEFAULT_EMBED_ID',
  'NEXT_PUBLIC_AITUBERKIT_EMBEDS',
  'NEXT_PUBLIC_EXTERNAL_LINKAGE_MODE',
  'NEXT_PUBLIC_EXTERNAL_LINKAGE_URL',
  'NEXT_PUBLIC_MESSAGE_RECEIVER_ENABLED',
  'NEXT_PUBLIC_OFFICIAL_SITE',
  'NEXT_PUBLIC_CLIENT_ID',
  'NEXT_PUBLIC_SITE_URL',

  // --- Realtime API ---
  'NEXT_PUBLIC_REALTIME_API_MODE',
  'NEXT_PUBLIC_REALTIME_API_MODE_CONTENT_TYPE',
  'NEXT_PUBLIC_REALTIME_API_MODE_VOICE',

  // --- OpenAI キー（直接参照用フォールバック） ---
  'NEXT_PUBLIC_OPENAI_API_KEY',
  'NEXT_PUBLIC_OPENAI_KEY',

  // --- 推論モデル設定 ---
  'NEXT_PUBLIC_REASONING_EFFORT',
  'NEXT_PUBLIC_REASONING_MODE',
  'NEXT_PUBLIC_REASONING_TOKEN_BUDGET',

  // --- UI・動作詳細設定 ---
  'NEXT_PUBLIC_ANGRY_EMOTIONS',
  'NEXT_PUBLIC_ANGRY_MOTION_GROUP',
  'NEXT_PUBLIC_BASE_PATH',
  'NEXT_PUBLIC_CHANGE_ENGLISH_TO_JAPANESE',
  'NEXT_PUBLIC_CHARACTER_POSITION',
  'NEXT_PUBLIC_CHARACTER_PRESET1',
  'NEXT_PUBLIC_CHARACTER_PRESET2',
  'NEXT_PUBLIC_CHARACTER_PRESET3',
  'NEXT_PUBLIC_CHARACTER_PRESET4',
  'NEXT_PUBLIC_CHARACTER_PRESET5',
  'NEXT_PUBLIC_CHARACTER_ROTATION',
  'NEXT_PUBLIC_CHAT_LOG_EDGE_OFFSET',
  'NEXT_PUBLIC_CHAT_LOG_MODE',
  'NEXT_PUBLIC_CHAT_LOG_POSITION',
  'NEXT_PUBLIC_CHAT_LOG_STYLE',
  'NEXT_PUBLIC_CHAT_LOG_WIDTH',
  'NEXT_PUBLIC_CONTINUOUS_MIC_LISTENING_MODE',
  'NEXT_PUBLIC_CUSTOM_PRESET_NAME1',
  'NEXT_PUBLIC_CUSTOM_PRESET_NAME2',
  'NEXT_PUBLIC_CUSTOM_PRESET_NAME3',
  'NEXT_PUBLIC_CUSTOM_PRESET_NAME4',
  'NEXT_PUBLIC_CUSTOM_PRESET_NAME5',
  'NEXT_PUBLIC_DEBUG_LOG',
  'NEXT_PUBLIC_DEMO_MODE',
  'NEXT_PUBLIC_DYNAMIC_RETRIEVAL_THRESHOLD',
  'NEXT_PUBLIC_ENABLE_MULTIMODAL',
  'NEXT_PUBLIC_FIXED_CHARACTER_POSITION',
  'NEXT_PUBLIC_HAPPY_EMOTIONS',
  'NEXT_PUBLIC_HAPPY_MOTION_GROUP',
  'NEXT_PUBLIC_HIDE_VIDEO_DISPLAY',
  'NEXT_PUBLIC_IMAGE_DISPLAY_POSITION',
  'NEXT_PUBLIC_INCLUDE_SYSTEM_MESSAGES_IN_CUSTOM_API',
  'NEXT_PUBLIC_INCLUDE_TIMESTAMP_IN_USER_MESSAGE',
  'NEXT_PUBLIC_INITIAL_SPEECH_TIMEOUT',
  'NEXT_PUBLIC_LIGHTING_INTENSITY',
  'NEXT_PUBLIC_MAX_TOKENS',
  'NEXT_PUBLIC_MULTIMODAL_AI_DECISION_PROMPT',
  'NEXT_PUBLIC_NEUTRAL_EMOTIONS',
  'NEXT_PUBLIC_NEUTRAL_MOTION_GROUP',
  'NEXT_PUBLIC_NO_SPEECH_TIMEOUT',
  'NEXT_PUBLIC_PRESET_QUESTIONS',
  'NEXT_PUBLIC_RELAXED_EMOTIONS',
  'NEXT_PUBLIC_RELAXED_MOTION_GROUP',
  'NEXT_PUBLIC_RESTRICTED_MODE',
  'NEXT_PUBLIC_SAD_EMOTIONS',
  'NEXT_PUBLIC_SAD_MOTION_GROUP',
  'NEXT_PUBLIC_SCREEN_ORIENTATION',
  'NEXT_PUBLIC_SETTINGS_TOGGLE_SHORTCUT',
  'NEXT_PUBLIC_SHOW_INTRODUCTION',
  'NEXT_PUBLIC_SHOW_MOUSE_CURSOR',
  'NEXT_PUBLIC_SHOW_PRESET_QUESTIONS',
  'NEXT_PUBLIC_SHOW_SILENCE_PROGRESS_BAR',
  'NEXT_PUBLIC_SHOW_THINKING_TEXT',
  'NEXT_PUBLIC_SURPRISED_EMOTIONS',
  'NEXT_PUBLIC_SURPRISED_MOTION_GROUP',
  'NEXT_PUBLIC_THINKING_POSE_ENABLED',
  'NEXT_PUBLIC_THINKING_POSE_ID',
  'NEXT_PUBLIC_USE_VIDEO_AS_BACKGROUND',
  'NEXT_PUBLIC_VOICE_INPUT_SHORTCUT',
  'NEXT_PUBLIC_WHISPER_TRANSCRIPTION_MODEL',
]

function listSourceFiles(dir: string): string[] {
  const entries = fs.readdirSync(dir, { withFileTypes: true })
  return entries.flatMap((entry) => {
    const fullPath = path.join(dir, entry.name)
    if (entry.name === '__tests__' || entry.name === '__mocks__') {
      return []
    }
    if (entry.isDirectory()) {
      return listSourceFiles(fullPath)
    }
    if (/\.tsx?$/.test(entry.name)) {
      return [fullPath]
    }
    return []
  })
}

function extractDeclaredVars(): Set<string> {
  const content = fs.readFileSync(ENV_EXAMPLE_PATH, 'utf-8')
  const matches = content.matchAll(/^(NEXT_PUBLIC_[A-Z0-9_]+)=/gm)
  return new Set(Array.from(matches, (m) => m[1]))
}

function extractReferencedVars(): Set<string> {
  const referenced = new Set<string>()
  for (const file of listSourceFiles(SRC_DIR)) {
    const content = fs.readFileSync(file, 'utf-8')
    for (const match of content.matchAll(/NEXT_PUBLIC_[A-Z0-9_]+/g)) {
      referenced.add(match[0])
    }
  }
  return referenced
}

describe('.env.example / NEXT_PUBLIC_* consistency', () => {
  const declaredVars = extractDeclaredVars()
  const referencedVars = extractReferencedVars()
  const excludedSet = new Set(EXCLUDED_FROM_ENV_EXAMPLE)

  it('should find declared and referenced variables', () => {
    expect(declaredVars.size).toBeGreaterThan(0)
    expect(referencedVars.size).toBeGreaterThan(0)
  })

  it('should not declare stale NEXT_PUBLIC_* variables unused by any source file', () => {
    const stale = Array.from(declaredVars)
      .filter(
        (v) =>
          !referencedVars.has(v) && !ALLOWED_UNREFERENCED_IN_CODE.includes(v)
      )
      .sort()

    expect(stale).toEqual([])
  })

  it('should account for all referenced variables in either .env.example or excluded list', () => {
    const unmanaged = Array.from(referencedVars)
      .filter((v) => !declaredVars.has(v) && !excludedSet.has(v))
      .sort()

    expect(unmanaged).toEqual([])
  })

  it('should not contain unreferenced variables in excluded list', () => {
    const staleExcluded = EXCLUDED_FROM_ENV_EXAMPLE.filter(
      (v) => !referencedVars.has(v)
    ).sort()

    expect(staleExcluded).toEqual([])
  })
})
